import type { Food } from '@/types/common/entities'

export const SAMPLE_FOODS: Food[] = [
  {
    id: 'bun-bo-hue',
    name: 'Bún bò Huế',
    emoji: '🍜',
    rating: 4.7,
    reviewCount: 1284,
    priceMin: 60,
    priceMax: 80,
    distanceMeters: 800,
    tags: ['Món nước', 'Việt Nam', 'Cay'],
  },
  {
    id: 'com-tam',
    name: 'Cơm tấm sườn bì',
    emoji: '🍚',
    rating: 4.5,
    reviewCount: 892,
    priceMin: 45,
    priceMax: 60,
    distanceMeters: 1200,
    tags: ['Cơm', 'Việt Nam', 'Phổ biến'],
  },
  {
    id: 'sushi-ca-hoi',
    name: 'Sushi cá hồi',
    emoji: '🍣',
    rating: 4.8,
    reviewCount: 2103,
    priceMin: 150,
    priceMax: 250,
    distanceMeters: 2500,
    tags: ['Nhật Bản', 'Healthy'],
  },
  {
    id: 'pho-ga',
    name: 'Phở gà',
    emoji: '🍲',
    rating: 4.6,
    reviewCount: 1567,
    priceMin: 50,
    priceMax: 70,
    distanceMeters: 500,
    tags: ['Món nước', 'Việt Nam'],
  },
  {
    id: 'banh-mi',
    name: 'Bánh mì thịt nướng',
    emoji: '🥖',
    rating: 4.4,
    reviewCount: 734,
    priceMin: 20,
    priceMax: 35,
    distanceMeters: 300,
    tags: ['Ăn vặt', 'Việt Nam'],
  },
  {
    id: 'mi-cay',
    name: 'Mì cay Hàn Quốc',
    emoji: '🌶️',
    rating: 4.3,
    reviewCount: 456,
    priceMin: 55,
    priceMax: 75,
    distanceMeters: 1800,
    tags: ['Hàn Quốc', 'Cay'],
  },
]
